### ISSUE TITLE
Add Mozilla/Seamonkey Composer to list of approved editors.

### ISSUE THREAD

**Issue by forkiesassds** [2003tech/2003page.ga#32]
1. **Is your feature request related to a problem? Please describe.**
Mozilla/Seamonkey composer can edit HTML files (and it's like frontpage express, but not by Microsoft)

2. **Describe the solution you'd like** (if first is false skip)
Add the programs to the approved editor list

3. **The features**
Add the logos Mozilla/Seamonkey composer to the approved editors

4. **In what file?**
/misc/promotionalmaterial/sealofapproval.png and misc/promotionalmaterial/sealofapproval/index.htm

**Comment by PF94** [comment]
While we haven't thought about Mozilla/Seamonkey composer, we think that it's a good idea. In the other hand, Word isn't best suited as a HTML editor. The feature only existed to convert Word documents into HTML pages.

**Comment by forkiesassds** [comment]
> I also think that if we added word in the approved editors seal, someone could be making their sub sites with Word 2010 or 2016, which isn't time appropriate.

What if you say that you have to use the period correct version of word?

**Comment by PF94** [comment]
I'm going to be against word, it's too basic of a site editor to be counted as a site editor.

**Comment by forkiesassds** [comment]
I've updated the material.
