### ISSUE TITLE
Optimize the CSS

### ISSUE THREAD

**Issue by PF94** [2003tech/2003page.ga#4]
You want to know why the Codefactor is F?, well, I've checked and it's all because of the Microsoft CSS,

Solution:

1. Optimize them regulary.
or
2. Ditch then, but it makes every site bland and broken.

**Comment by TLWXPUser** [comment]
I have just done a branch where we can do the changes [Slave]

**Comment by TLWXPUser** [comment]
btw i recalculated the score before my commitment and its a big f

**Comment by PF94** [comment]
meh, i'm not going to waste my time fixing shitty css errors

**Comment by PF94** [comment]
I don't want to say this, but, fixing the CSS is a big waste of time since Frontpage always overwrites them.

Frontpage 2003 was made with IE6 in mind, not with modern-day browsers. Thus, 2003page will still use umoptimized css for convience's sake.

**Comment by forkiesassds** [comment]
>fixing the CSS is a big waste of time since Frontpage always overwrites them.

I don't think so, if we remove the `mstheme` comment and remove the meta tag for the theme we could optimize it.
