### ISSUE TITLE
2003page doesn't load anymore on old browsers on Windows XP due to "Let's Encrypt".

### ISSUE THREAD

**Issue by PF94** [2003tech/2003page.ga#49]
~~I have a feeling it's due to the "Let's Encrypt" certificate, which uses TLS 1.2,~~  It is due to the TLS 1.2-required certificate, This means the only solution is to get the PosReady updates, which could take forever to install them.

I'm just going to paste this
https://msfn.org/board/topic/178092-enable-tls-11-and-12-in-windows-xp-correctly/

If anyone knows on how to fix this problem w/o requiring people to update XP, let me know.

**Comment by Mdstumpfy123** [comment]
who the fuck uses xp anymore for 2020 websites

**Comment by PF94** [comment]
Also, Google lists the HTTPS version of 2003page, which prompted a error when i was using a Android VM for a unrelated project (Chaziz Android)
