### ISSUE TITLE
2003page Join Request (WAITING FOR RESPONSE)

### ISSUE THREAD

**Issue by EpicTaco404** [2003tech/2003page.ga#6]
I want to add my TacoShell website to 2003page.ga.

**Comment by PF94** [comment]
I have added you, please accept the request you got on your email. If you do not find it. Go to https://github.com/2003tech/2003page.ga/invitations.

**Comment by PF94** [comment]
I will be reopening the issue up until EpicTaco appects the request.

@EpicTaco404 please appect the request at https://github.com/2003tech/2003page.ga/invitations.
