### ISSUE TITLE
Make main page more mid-to-late-2000s-y

### ISSUE THREAD

**Issue by PF94** [2003tech/2003page.ga#66]
Title says it all, IDFK how

**Comment by forkiesassds** [comment]
Give me some examples of late 2000's sites.

**Comment by PF94** [comment]
Is that another attempt at trying to make 2003page still the cliche "early-00s" website-revival?

**Comment by forkiesassds** [comment]
![image](https://user-images.githubusercontent.com/54495659/77318872-7ce03d00-6d16-11ea-97ad-b56a04b80795.png)
This is what I was working on so far.
