### ISSUE TITLE
Void issue on Main Page's CSS on Firefox

### ISSUE THREAD

**Issue by PF94** [2003tech/2003page.ga#73]
(TESTED WITH VERSION 74 AND VERSION 20)

This issue appears below the flag counter (or below the 88x31 buttons for those who have adblock), I don't know when this first appeared, but i'm guessing it first appeared around versions 5 to 15.

This issue doesn't appear on Edgemium/Chromedge.

![image](https://user-images.githubusercontent.com/45898787/77462102-ff7e0080-6dd9-11ea-93a2-500a73a123f1.png)

Mozilla never fixed this bug for some reason, ehh,

Pulling #72 will close this issue.

**Comment by forkiesassds** [comment]
The problem comes from the fact I used Chrome to develop the new CSS
