### ISSUE TITLE
404 breaks in subdirectories.

### ISSUE THREAD

**Issue by forkiesassds** [2003tech/2003page.ga#80]
Basically if I go to http://2003page.ga/invalid 404 works as intended, but in http://2003page.ga/invalid/directory 404 fails to load the assets.

**Comment by EricZhang456** [comment]
oh no it doesn't

**Comment by forkiesassds** [comment]
This issue is caused due to the fact GitHub pages is completely static, no PHP, no .htaccess only Jekyll

**Comment by EricZhang456** [comment]
No it's still broken, broken for /invaild/file/xdddd

**Comment by PF94** [comment]
![image](https://user-images.githubusercontent.com/45898787/78456516-2c4fd480-7672-11ea-8a70-8e57d22b0b60.png)
I fixed the issue, since, a day ago, lmao.

**Comment by EricZhang456** [comment]
lmao be local-friendly
