### ISSUE TITLE
Main Page: The font is serif on Ubuntu 8.04 and earlier (8.10, 9.04 and 9.10 untested yet)

### ISSUE THREAD

**Issue by PF94** [2003tech/2003page.ga#90]
I have found this issue while playing around with Ubuntu 8.04.4 LTS, which was fully updated and included two old versions of Firefox, and a old version of Seamonkey. This all happend on a 1 hour and a half long "Chaziz Tech" livestream.
![VirtualBox_(ubuntu) Ubuntu 8 04 LTS_08_04_2020_13_38_09](https://user-images.githubusercontent.com/45898787/78815450-4d7c3200-799e-11ea-807a-16dbeb688082.png)

Ubuntu 8.04 uses a serif font because the font Ubuntu did not exist until 10.10.

However, 10.04 seems to use what appears to be Verdana? I can't verify because my virtual machine has got a bug in which a random window pops up (also it seems to now call itself "lubuntu" when shutting down)
![VirtualBox_(ten-oh-four) Ubuntu 10 04 LTS_08_04_2020_13_44_05](https://user-images.githubusercontent.com/45898787/78816038-1bb79b00-799f-11ea-9493-8551cd58be53.png)

I know anything from 4.10 to 8.04 will have this issue, however i have yet to try 8.10, 9.04 and 9.10.

My solution is to include whatever sans-serif font Ubuntu 8.04 has.

**Comment by forkiesassds** [comment]
I have fixed Shadow's button.

**Comment by PF94** [comment]
Oh.

**Comment by EricZhang456** [comment]
add the fonts to the website?
