### ISSUE TITLE
R̶o̶v̶e̶r̶ ̶C̶S̶S̶ ̶i̶s̶ ̶b̶r̶o̶k̶e̶n̶ ̶d̶u̶e̶ ̶t̶o̶ ̶#̶7̶8̶6̶3̶c̶9̶9̶ ̶+̶ Plans for "Special CSS".

### ISSUE THREAD

**Issue by PF94** [2003tech/2003page.ga#91]
Now, you may ask, "Crappa, why did you do this?!?", well, that's because. I have the idea of changing the colors during a holiday, for example, orange-black for Halloween, red-green for Christmas, red-blue for July 4th, etc. I wanted to make the Rover CSS a template for what Special CSS should be.

Now, this is a dumb idea, but it makes it so that 2003page doesn't look dead and abandonned or even planned to be shutdown (You know what happend with MessengerGeekia). This also makes 2003page somewhat fresh, but not in the rate of mid-2019 where we were changing the CSS (and thus making the codefactor F) every 2 days or what-not, or in a rate of a Doogle (not the dog from that british cartoon).

Done with the rambling, -PF94

**Comment by forkiesassds** [comment]
We could fix this if we use some dynamic thing or something.

**Comment by PF94** [comment]
i still want compatilbity for at least the unsupported browsers (pre-ie4)

**Comment by forkiesassds** [comment]
Fixed it, make sure the priority of the CSS if some other file you don't want to use overrides it.

**Comment by PF94** [comment]
ICTY, can you not remove the fixed problems? just strike out the fixed problem.

(you also did this for #90)

**Comment by PF94** [comment]
Please refrain from rollbacking, this is not Geekia.

**Comment by forkiesassds** [comment]
It is impossible to strike-through in a title.

**Comment by PF94** [comment]
dude i littearly striked it out using a external site lmao

**Comment by forkiesassds** [comment]
Looks like an underline on my machine

**Comment by PF94** [comment]
i'd blame the font.

**Comment by forkiesassds** [comment]
I have smooth fonts off and I am on Windows

**Comment by EricZhang456** [comment]
Are you idiot?
It looks fine on my machine.
If you want pre-IE4 support, please put this line in `<head>`
```
<!--[if lt IE 4]>
lol put your m$ trash priority css here
<![endif]--> 
```

**Comment by EricZhang456** [comment]
btw, what is "special css"

**Comment by PF94** [comment]
Special CSS? It's where the background changes color for a event, mostly seasonal.

**Comment by EricZhang456** [comment]
oh crap

**Comment by EricZhang456** [comment]
![图片](https://user-images.githubusercontent.com/32814750/78949818-63553880-7aff-11ea-8e7d-bc9944874088.png)
Well your site didn't pass CSS 2.1 check but passed CSS 3 check

**Comment by EricZhang456** [comment]
> 5. CSS3, too modern, and old browsers choke hard on CSS3, read the CSS 2.2 speficiation

lol

**Comment by PF94** [comment]
Eric, for fuck sakes, It passed the check, it's just a minor warning that doesn't do anything.

**Comment by EricZhang456** [comment]
lol, 2 errors, *"This version of CSS does not contains `background: linear-gradient`"*

**Comment by PF94** [comment]
The linear-gradient shit will not be worked on.

**Comment by forkiesassds** [comment]
What special events should we cover?

**Comment by PF94** [comment]
* New Years (January 1st, Rainbow like the Gamerias?)
* Valentines Day (Febuary 24th, Red-to-pink)
* 2003page's Aniversary (March 5th, Grey-to-black)
* MessengerGeekia's Aniversary (October 18th, White to grey)
* Halloween (October 31st, Orange to black)

Here's what i have

**Comment by EricZhang456** [comment]
Add a Feb, 1st. It's Rover's birthday!

**Comment by PF94** [comment]
I added in to the reply.

**Comment by EricZhang456** [comment]
I think we need js for this

**Comment by PF94** [comment]
nope, or else a issue will open about "WHY THE FUCK DOES MY INTERNET EXPLORER 6 SCREAM OUT A ERROR EACH TIME I GOT TO 2003PAGE11!1!".

**Comment by EricZhang456** [comment]
Then how are you going to do this

**Comment by EricZhang456** [comment]
https://stackoverflow.com/questions/4701940/change-background-with-css-on-particular-date

Either dynamic or JS

**Comment by EricZhang456** [comment]
IE 6 complains about every js script on the planet

**Comment by PF94** [comment]
true, but instand of any useless shitty scripts, it'll be manual, while this may cause some the special css to be accidently skipped or be stuck for much longer, i don't want to bother with jav for now.

**Comment by EricZhang456** [comment]
We can write specific JS for IE, and use the `if IE` to do this

**Comment by PF94** [comment]
i can't be bothered with that right nwo.

**Comment by forkiesassds** [comment]
> * New Years (January 1st, Rainbow like the Gamerias?)
> * Rover's birthday (Febuary 1st, pre-existing rover CSS file)
> * Valentines Day (Febuary 24th, Red-to-pink)
> * 2003page's Aniversary (March 5th, Grey-to-black)
> * MessengerGeekia's Aniversary (October 18th, White to grey)
> * Halloween (October 31st, Orange to black)
> * Christmas (December 24th to 26th, red to green)
>   Here's what i have

1. IE8 and bellow only allows me to use one color for gradient
2. How do I make some of the gradients look good
3. How do I make it load the specific CSS without using JS or PHP?
4. TIMEZONES!

**Comment by EricZhang456** [comment]
@forkiesassds he means to change the css manually when the day comes, sounds dumb right?

Also it seems that the timezone problem only effects me the most, so, hmm...

**Comment by forkiesassds** [comment]
> sounds dumb right?

Yea

> Also it seems that the timezone problem only effects me the most, so, hmm...

PF94 lives in Canada, you live in China and I live in Europe.

**Comment by forkiesassds** [comment]
Either migrate from GitHub pages to use PHP or JS.

**Comment by PF94** [comment]
I am not going to include PHP cause if a new version comes out, there's a chance EVERYTHING will be fucked, look what happend to Alessio's openMusic, the PHP broke off, now it's dead.

**Comment by forkiesassds** [comment]
Do you want labor or me having to use JS which some people don't want to use?

**Comment by PF94** [comment]
try the javascript, but test IE6, if it throws up a javascript error, no.

I also added some new events, including this random event from the original Animal Crossing for the Gamecube.

**Comment by PF94** [comment]
> @PF94
> Are you idiot?
> It looks fine on my machine.
> If you want pre-IE4 support, please put this line in `<head>`
> 
> ```
>  
> ```

I guess we can use this... maybe?

**Comment by EricZhang456** [comment]
Dude, our index is HTML 4

**Comment by EricZhang456** [comment]
IE 6 throws an error is the JS is a standard JS, not M$ priority JS.

**Comment by PF94** [comment]
"Standard JS" is Javascript
"M$ priority JS" is JScript

These two, while have simillar names, and they both use the ECMAScript specification, are different in some way or the other.

**Comment by forkiesassds** [comment]
> * Easter (Easter Sunday, Light blue to blue, If you don't know what date it is, check [name of your search engine] or talk to your villagers on AC:NL/AC:NH.)

Easter Sunday's date varies from year to year

**Comment by forkiesassds** [comment]
I have made it possible using JS, PF please check it in IE6

**Comment by forkiesassds** [comment]
![image](https://user-images.githubusercontent.com/54495659/79065203-3ba8d080-7cb7-11ea-9bf8-bfab76ff1780.png)
IE7 does not seem to throw a script error and seems to detect today is easter.

**Comment by EricZhang456** [comment]
Try IE 6

**Comment by forkiesassds** [comment]
Well the thing is I don't have an VM that can run IE6, but IE11's emulation supports IE5 and there were no errors.

**Comment by PF94** [comment]
I will be closing this for a new discussion issue
