### ISSUE TITLE
2003page and it's rise and fall and rise and possible-future-fall.

### ISSUE THREAD

**Issue by PF94** [2003tech/2003page.ga#92]
Most of 2003page's commits have been about the Main Page lately, subsites are abandonned, with only 2-20 commits and then the contributer quits. 

I'd blame the 2003site.gq incident which caused most people to quit (cause they were now locked from modifying their subsites), this caused 2003page to be mostly slient, until when two major contributors, ICTY and EAE, however this rise of activity may disappear, making 2003page a wasteland yet again, There's 5 peaks of activity on this project

1. May 2019 (launch of 2003page)
2. June 2019 (when 8-ish contributors joined)
3. September 2019 (The NT5.0 Era)
4. January 2020 (Upwader joining, and me archving junk)
5. March-April 2020 (Eric joining, and me getting back on 2003page)

Recently, there has been more commits than what 2003page had in it's first month, however, it seems to be falling back to where it's usually at, total slience.

It seems that 2003page is a project people knows for a week, then forgets about it for their rest of their lives.

This has also happend with MessengerGeekia, but people just forgot about it for good, which made it easier to shut it down. 2003page will not be shutdown unless if it's a wasteland for more than 2 years. No, i'm not trying to make a threat, but let's be real here, 2003page is a project, not a multi-billion dollar website.

2003page is really, the only project remaining for 2003tech, yes, there's Sample Title Game, but it has been put on hold cause we can't be bothered to code (and fix that shitty slow jump).

I also want to move 2003tech away from MessengerGeek, which has been sorta done already, with the shutdown of Geekia, but, if you think about it, only 1 contributor doesn't originate from MessengerGeek, which is Upwader, from AIM Pheonix, however, MG and Phoenix overlap quite a little bit, however Upwader was truly from the Phoneix part, not the MG part, so i guess it counts?

Anyways, i want to expand 2003page, uh, that's all i have to say.

**Comment by EricZhang456** [comment]
Most of the 2003page *"subsites"* are not finished yet, they are just a WIP message.

**Comment by PF94** [comment]
True and I somehow got one of the original June-2019 contributors to reply something.
![Screenshot_20200414-122954_Discord](https://user-images.githubusercontent.com/45898787/79249770-c02c5800-7e4b-11ea-8bb0-5f9aed170f65.jpg)
(KF9)

**Comment by EricZhang456** [comment]
https://github.com/2003tech/2003page.ga/graphs/contributors

Really *"facepalming"*

**Comment by EricZhang456** [comment]
There is even a month that has no commits what so ever

**Comment by PF94** [comment]
Obviously cause i was taking a break and everyone seemily left.
